on: [push]

jobs:
  mediawiki-extension-action-sqlite:
    runs-on: ubuntu-latest
    name: Dummy extension test (sqlite)
    steps:
      # check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test dummy extension
        uses: ./ # Uses an action in the root directory
        id: extension-test
        with:
          php: 7.4
          mwbranch: REL1_39
          extension: DummyExtension
          dependencies: "[{ \"path\": \"mediawiki/extensions/examples\", \"repository\": \"wikimedia/mediawiki-extensions-examples\" }]"
          extra_file: .github/PHPUnitSettings.php
